<?php
namespace milkyway\comments\components;

use backend\components\MyController;

class MyCommentsController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
