<?php

namespace milkyway\socials\models\table;

use cheatsheet\Time;
use milkyway\socials\models\query\SocialsQuery;
use modava\auth\models\User;
use Yii;
use yii\db\ActiveRecord;

class SocialsTable extends \yii\db\ActiveRecord
{
    const STATUS_DISABLED = 0;
    const STATUS_PUBLISHED = 1;
    const TYPE_IMAGE = 0;
    const TYPE_ICON = 1;
    const TYPE = [
        self::TYPE_IMAGE => 'Hình ảnh',
        self::TYPE_ICON => 'Icon'
    ];

    public $pathImage;
    public $urlImage;

    public function init()
    {
        $this->pathImage = Yii::getAlias('@frontend/web/uploads/socials');
        $this->urlImage = Yii::getAlias('@frontendUrl/uploads/socials');
        parent::init(); // TODO: Change the autogenerated stub
    }

    public static function tableName()
    {
        return 'socials';
    }

    public static function find()
    {
        return new SocialsQuery(get_called_class());
    }

    public function getImage()
    {
        if ($this->type == self::TYPE_IMAGE && !is_dir($this->pathImage . '/' . $this->image) && file_exists($this->pathImage . '/' . $this->image)) {
            return Yii::$app->assetManager->publish($this->pathImage . '/' . $this->image)[1];
        }
        return null;
    }

    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [
            'redis-social-get-by-id-' . $this->id,
            'redis-social-get-all'
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [
            'redis-social-get-by-id-' . $this->id,
            'redis-social-get-all'
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUserCreated()
    {
        return $this->hasOne(User::class, ['id' => 'created_by']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUserUpdated()
    {
        return $this->hasOne(User::class, ['id' => 'updated_by']);
    }

    public static function getById($id, $published = false, $data_cache = YII2_CACHE)
    {
        $cache = Yii::$app->cache;
        $key = 'redis-social-get-by-id-' . $id;
        $data = $cache->get($key);
        if ($data == false || $data_cache === false) {
            $query = self::find()->where([self::tableName() . '.id' => $id]);
            if ($published === true) $query->published();
            $data = $query->one();
            $cache->set($key, $data);
        }
        return $data;
    }

    public static function getAll($published = false, $data_cache = YII2_CACHE)
    {
        $cache = Yii::$app->cache;
        $key = 'redis-social-get-all';
        $data = $cache->get($key);
        if ($data == false || $data_cache === false) {
            $query = self::find()->sort();
            if ($published === true) $query->published();
            $data = $query->all();
            $cache->set($key, $data);
        }
        return $data;
    }
}
