<?php
namespace milkyway\contact\components;

use backend\components\MyController;

class MyContactController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
