<?php
namespace milkyway\manual\widgets;

class NavbarWidgets extends \yii\base\Widget
{
    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function run()
    {
        return $this->render('navbarWidgets', []);
    }
}
