<?php
namespace modava\news\components;

use backend\components\MyController;

class MyNewsController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
