<?php
namespace milkyway\manual\components;

use backend\components\MyController;

class MyManualController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
