<?php
namespace milkyway\team\components;

use backend\components\MyController;

class MyTeamController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
