<?php

namespace milkyway\manual\models\table;

use cheatsheet\Time;
use milkyway\manual\models\PermissionManual;
use milkyway\manual\models\query\UserManualQuery;
use Yii;
use yii\db\ActiveRecord;

class UserManualTable extends \yii\db\ActiveRecord
{
    const STATUS_DISABLED = 0;
    const STATUS_PUBLISHED = 1;

    public static function tableName()
    {
        return 'user_manual';
    }

    public static function find()
    {
        return new UserManualQuery(get_called_class());
    }

    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function getForPermission()
    {
        return $this->hasOne(PermissionManual::class, ['id' => 'for_permission']);
    }

    public function getUserCreated()
    {
        return $this->hasOne(Yii::$app->user->identityClass, ['id' => 'created_by']);
    }

    public function getUserUpdated()
    {
        return $this->hasOne(Yii::$app->user->identityClass, ['id' => 'updated_by']);
    }
}
