<?php

namespace milkyway\language\models;

use common\helpers\MyHelper;
use common\models\User;
use milkyway\language\LanguageModule;
use milkyway\language\models\table\LanguageTable;
use yii\behaviors\AttributeBehavior;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\SluggableBehavior;
use yii\db\ActiveRecord;
use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "language".
 *
 * @property int $id
 * @property string $name
 * @property string $slug
 * @property string $image
 * @property int $status
 * @property int $sort Thứ tự
 * @property int $created_at
 * @property int $created_by
 * @property int $updated_at
 * @property int $updated_by
 *
 * @property User $createdBy
 * @property User $updatedBy
 */
class Language extends LanguageTable
{
    public $toastr_key = 'language';
    public $iptImage;
    private $oldImage;

    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                [
                    'class' => BlameableBehavior::class,
                    'createdByAttribute' => 'created_by',
                    'updatedByAttribute' => 'updated_by',
                ],
                'timestamp' => [
                    'class' => 'yii\behaviors\TimestampBehavior',
                    'preserveNonEmptyValues' => true,
                    'attributes' => [
                        ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                        ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                    ],
                ],
                'is_default' => [
                    'class' => AttributeBehavior::class,
                    'attributes' => [
                        ActiveRecord::EVENT_BEFORE_INSERT => ['is_default'],
                        ActiveRecord::EVENT_BEFORE_UPDATE => ['is_default'],
                    ],
                    'value' => function () {
                        if ($this->is_default === null) {
                            $query = self::find()->where([self::tableName() . '.is_default' => self::STATUS_PUBLISHED])->published();
                            if ($this->primaryKey === null) $query->andWhere(self::tableName() . '.id IS NOT null');
                            else $query->andWhere(['<>', self::tableName() . '.id', $this->primaryKey]);
                            return $query->count() > 0 ? 0 : 1;
                        }
                        return $this->is_default;
                    }
                ],
            ]
        );
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'code'], 'required'],
            [['code'], 'unique'],
            [['status', 'is_default'], 'integer'],
            [['name', 'image'], 'string', 'max' => 255],
            [['name'], 'unique'],
            [['iptImage'], 'file', 'extensions' => ['jpg', 'jpeg', 'png'], 'maxSize' => 2 * 1024 * 1024, 'wrongExtension' => 'Chỉ chấp nhận định dạng file: {extensions}'],
            [['is_default'], 'checkIsDefault']
        ];
    }

    public function checkIsDefault()
    {
        if (!$this->hasErrors() && $this->is_default === self::STATUS_PUBLISHED) {
            $check_other_default = self::getDefaultLanguage();
            if ($check_other_default != null && $check_other_default->id != $this->primaryKey) {
                $this->addError('is_default', LanguageModule::t('language', 'Đã có ngôn ngữ mặc định'));
            }
        }
    }

    public function beforeSave($insert)
    {
        $this->oldImage = $this->getOldAttribute('image');
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $iptImage = UploadedFile::getInstance($this, 'iptImage');
        if ($iptImage != null) {
            $imageName = $iptImage->baseName . '-' . time() . '.' . $iptImage->extension;
            if ($iptImage->saveAs($this->pathImage . '/' . $imageName)) {
                $this->updateAttributes([
                    'image' => $imageName
                ]);
                if (file_exists($this->pathImage . '/' . $this->oldImage)) {
                    @unlink($this->pathImage . '/' . $this->oldImage);
                }
            }
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => LanguageModule::t('language', 'ID'),
            'name' => LanguageModule::t('language', 'Name'),
            'code' => LanguageModule::t('language', 'Code'),
            'image' => LanguageModule::t('language', 'Image'),
            'status' => LanguageModule::t('language', 'Status'),
            'is_default' => LanguageModule::t('language', 'Default'),
            'created_at' => LanguageModule::t('language', 'Created At'),
            'created_by' => LanguageModule::t('language', 'Created By'),
            'updated_at' => LanguageModule::t('language', 'Updated At'),
            'updated_by' => LanguageModule::t('language', 'Updated By'),
        ];
    }
}
