<?php

namespace milkyway\news\models\table;

use cheatsheet\Time;
use Yii;
use yii\db\ActiveRecord;

class NewsTagsTable extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return 'news_tags';
    }

    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [
            'redis-news-tags-get-by-tag-' . $this->tag
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [
            'redis-news-tags-get-by-tag-' . $this->tag
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public static function getByTag($tag, $data_cache = YII2_CACHE)
    {
        $cache = Yii::$app->cache;
        $key = 'redis-news-tags-get-by-tag-' . $tag;
        $data = $cache->get($key);
        if ($data == false || (!defined('YII2_CACHE') || YII2_CACHE === false) || $data_cache === false) {
            $query = self::find()->where([self::tableName() . '.tag' => $tag]);
            $data = $query->one();
            if (defined('YII2_CACHE') && YII2_CACHE === true) $cache->set($key, $data);
        }
        return $data;
    }
}
