<?php

namespace milkyway\news\models\table;

use common\models\User;
use frontend\models\NewsCategory;
use milkyway\news\models\query\NewsQuery;
use Yii;

class NewsTable extends \yii\db\ActiveRecord
{
    const STATUS_DISABLED = 0;
    const STATUS_PUBLISHED = 1;
    public $pathImage;
    public $urlImage;

    public function init()
    {
        $this->pathImage = Yii::getAlias('@frontend/web/uploads/news');
        $this->urlImage = Yii::getAlias('@frontendUrl/uploads/news');
        parent::init(); // TODO: Change the autogenerated stub
    }

    public static function tableName()
    {
        return 'news';
    }

    public static function find()
    {
        return new NewsQuery(get_called_class());
    }

    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [
            'redis-news-get-by-id-' . $this->id,
            'redis-news-get-by-slug-' . $this->slug,
            'redis-news-get-by-category-' . $this->category,
            'redis-news-get-by-alias-' . $this->alias,
            'redis-news-get-news-check-hot-' . $this->categoryHasOne->type,
            'redis-news-get-relate-news-' . $this->id,
            'redis-news-get-recommend-news-' . $this->id,
            'redis-news-get-all',
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [
            'redis-news-get-by-id-' . $this->id,
            'redis-news-get-by-slug-' . $this->slug,
            'redis-news-get-by-category-' . $this->category,
            'redis-news-get-by-alias-' . $this->alias,
            'redis-news-get-news-check-hot-' . $this->categoryHasOne->type,
            'redis-news-get-relate-news-' . $this->id,
            'redis-news-get-recommend-news-' . $this->id,
            'redis-news-get-all',
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUserCreated()
    {
        return $this->hasOne(User::class, ['id' => 'created_by']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUserUpdated()
    {
        return $this->hasOne(User::class, ['id' => 'updated_by']);
    }

    public function getCategoryHasOne()
    {
        return $this->hasOne(NewsCategoryTable::class, ['id' => 'category']);
    }

    public function getNewsLanguage()
    {
        return $this->hasMany(NewsLanguageTable::class, ['news_id' => 'id'])->indexBy('language_id');
    }

    public function getNewsImagesHasMany()
    {
        return $this->hasMany(NewsImagesTable::class, ['news_id' => 'id']);
    }

    public function getImage()
    {
        if (file_exists($this->pathImage . '/' . $this->image)) {
            return Yii::$app->assetManager->publish($this->pathImage . '/' . $this->image)[1];
        }
        return null;
    }

    public static function getById($id)
    {
        $cache = Yii::$app->cache;
        $key = 'redis-news-get-by-id-' . $id;
        $data = $cache->get($key);
        if ($data == false) {
            $query = self::find()->where([self::tableName() . '.id' => $id]);
            $data = $query->one();
            $cache->set($key, $data);
        }
        return $data;
    }

    public static function getBySlug($slug)
    {
        $cache = Yii::$app->cache;
        $key = 'redis-news-get-by-slug-' . $slug;
        $data = $cache->get($key);
        if ($data == false) {
            $query = self::find()->where([self::tableName() . '.slug' => $slug]);
            $data = $query->one();
            $cache->set($key, $data);
        }
        return $data;
    }

    public static function getNewsCheckHot($type = null, $data_cache = YII2_CACHE)
    {
        $cache = Yii::$app->cache;
        $key = 'redis-news-get-news-check-hot-' . $type;
        $data = $cache->get($key);
        if ($data == false || $data_cache === false) {
            $query = self::find()->where([
                self::tableName() . '.hot' => self::STATUS_PUBLISHED,
            ]);
            if ($type !== null) $query->joinWith(['categoryHasOne'])->andWhere([
                NewsCategory::tableName() . '.type' => $type
            ]);
            $query->sort(SORT_DESC)->published();
            $data = $query->all();
            $cache->set($key, $data);
        }
        return $data;
    }

    public static function getAll()
    {
        $cache = Yii::$app->cache;
        $key = 'redis-news-get-all';
        $data = $cache->get($key);
        if ($data == false) {
            $query = self::find()->sort();
            $data = $query->all();
            $cache->set($key, $data);
        }
        return $data;
    }

    public static function getByCategory($category = null, $limit = null)
    {
        $cache = Yii::$app->cache;
        $key = 'redis-news-get-by-category-' . $category;
        $data = $cache->get($key);
        if ($data == false) {
            $query = self::find()->where([self::tableName() . '.category' => $category]);
            if ($limit != null) $query->limit($limit)->offset(0);
            $query->sort();
            $data = $query->all();
            $cache->set($key, $data);
        }
        return $data;
    }

    public static function getQueryByAlias($alias = null)
    {
        $query = self::find()->where(self::tableName() . ".alias LIKE '{$alias}/%'");
        $query->sort();
        return $query;
    }

    public static function getByAlias($alias = null, $limit = null)
    {
        $cache = Yii::$app->cache;
        $key = 'redis-news-get-by-alias-' . $alias;
        $data = $cache->get($key);
        if ($data == false) {
            $query = self::find()->where(self::tableName() . ".alias LIKE '{$alias}/%'");
            if ($limit != null) $query->limit($limit)->offset(0);
            $query->sort();
            $data = $query->all();
            $cache->set($key, $data);
        }
        return $data;
    }

    public static function getRelateNews($id = null, $limit = null)
    {
        $cache = Yii::$app->cache;
        $key = 'redis-news-get-relate-news-' . $id;
        $data = $cache->get($key);
        if ($data == false) {
            $news = self::getById($id);
            if ($news == null) return [];
            $query = self::find()->where([self::tableName() . '.category' => $news->category])->andWhere(['<>', self::tableName() . '.id', $id])->published()->sort();
            if ($limit != null) $query->limit($limit)->offset(0);
            $data = $query->all();
            $cache->set($key, $data);
        }
        return $data;
    }

    public static function getRecommendNews($id = null, $limit = null, $data_cache = YII2_CACHE)
    {
        $cache = Yii::$app->cache;
        $key = 'redis-news-get-recommend-news-' . $id;
        $data = $cache->get($key);
        if ($data == false || $data_cache === false) {
            $news = self::getById($id);
            if ($news == null) return [];
            $alias = '/' . explode('/', $news->alias)[1];
            $query = self::find()->where(self::tableName() . ".alias LIKE '{$alias}%'")->andWhere(['<>', self::tableName() . '.id', $id])->published()->sort();
            if ($limit != null) $query->limit($limit)->offset(0);
            $data = $query->all();
            $cache->set($key, $data);
        }
        return $data;
    }
}
