<?php

namespace milkyway\news\models\table;

use cheatsheet\Time;
use Yii;
use yii\db\ActiveRecord;

class NewsImagesTable extends \yii\db\ActiveRecord
{
    public $pathImage;
    public $urlImage;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->pathImage = Yii::getAlias('@frontend/web/uploads/news/images');
        $this->urlImage = Yii::getAlias('@frontendUrl/uploads/news/images');
    }

    public static function tableName()
    {
        return 'news_images';
    }

    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [
            'redis-news-images-get-by-id-' . $this->id
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        if ($this->getImage() != null) @unlink($this->pathImage . '/' . $this->image);
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [
            'redis-news-images-get-by-id-' . $this->id
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function getNewsHasOne()
    {
        return $this->hasOne(NewsTable::class, ['id' => 'news_id']);
    }

    public function getImage()
    {
        if (file_exists($this->pathImage . '/' . $this->image)) {
            return Yii::$app->assetManager->publish($this->pathImage . '/' . $this->image)[1];
        }
        return null;
    }

    public static function getById($id)
    {
        $cache = Yii::$app->cache;
        $key = 'redis-news-images-get-by-id-' . $id;
        $data = $cache->get($key);
        if ($data == false) {
            $query = self::find()->where([self::tableName() . '.id' => $id]);
            $data = $query->one();
            $cache->set($key, $data);
        }
        return $data;
    }
}
