<?php

namespace milkyway\news\models\table;

use common\models\User;
use milkyway\language\models\table\LanguageTable;
use milkyway\news\models\query\NewsCategoryQuery;
use Yii;

class NewsCategoryTable extends \yii\db\ActiveRecord
{
    const STATUS_DISABLED = 0;
    const STATUS_PUBLISHED = 1;

    public $pathImage;
    public $urlImage;

    public function init()
    {
        $this->pathImage = Yii::getAlias('@frontend/web/uploads/news-category');
        $this->urlImage = Yii::getAlias('@frontendUrl/uploads/news-category');
        parent::init(); // TODO: Change the autogenerated stub
    }

    public static function tableName()
    {
        return 'news_category';
    }

    public static function find()
    {
        return new NewsCategoryQuery(get_called_class());
    }

    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [
            'redis-news-category-get-by-id-' . $this->id,
            'redis-news-category-get-all',
            'redis-news-category-get-by-slug-' . $this->slug
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [
            'redis-news-category-get-by-id-' . $this->id,
            'redis-news-category-get-all',
            'redis-news-category-get-by-slug-' . $this->slug
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUserCreated()
    {
        return $this->hasOne(User::class, ['id' => 'created_by']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUserUpdated()
    {
        return $this->hasOne(User::class, ['id' => 'updated_by']);
    }

    public function getCategoryHasOne()
    {
        return $this->hasOne(self::class, ['id' => 'category']);
    }

    public function getNewsCategoryLanguage()
    {
        return $this->hasMany(NewsCategoryLanguageTable::class, ['news_category_id' => 'id'])->indexBy('language_id');
    }

    public static function getById($id)
    {
        $cache = Yii::$app->cache;
        $key = 'redis-news-category-get-by-id-' . $id;
        $data = $cache->get($key);
        if ($data == false) {
            $query = self::find()->where([self::tableName() . '.id' => $id]);
            $data = $query->one();
            $cache->set($key, $data);
        }
        return $data;
    }

    public static function getBySlug($slug)
    {
        $cache = Yii::$app->cache;
        $key = 'redis-news-category-get-by-slug-' . $slug;
        $data = $cache->get($key);
        if ($data == false) {
            $query = self::find()->where([self::tableName() . '.slug' => $slug]);
            $data = $query->one();
            $cache->set($key, $data);
        }
        return $data;
    }

    public static function getAll()
    {
        $cache = Yii::$app->cache;
        $key = 'redis-news-category-get-all';
        $data = $cache->get($key);
        if ($data == false) {
            $query = self::find()->sort();
            $data = $query->one();
            $cache->set($key, $data);
        }
        return $data;
    }

    public static function getMenu($current = null, $category = null, $get_published = true, $data = null, $prefix = '|--')
    {
        if ($data == null) $data = [];
        $default_language = LanguageTable::getDefaultLanguage();
        $query = self::find()->joinWith(['newsCategoryLanguage'])->where([self::tableName() . '.category' => $category])->sort()->groupBy([self::tableName() . '.id']);
        if ($get_published === true) $query->published();
        $rows = $query->all();
        if (count($rows) > 0) {
            foreach ($rows as $row) {
                if ($current === $row->primaryKey) continue;
                $language = $default_language !== null ? $default_language->primaryKey : array_keys($row->newsCategoryLanguage)[0];
                $data[$row->primaryKey] = [
                    'id' => $row->primaryKey,
                    'name' => $prefix . $row->newsCategoryLanguage[$language]->name
                ];
                $data = self::getMenu($current, $row->primaryKey, $get_published, $data, $prefix . '|--');
            }
        }
        return $data;
    }
}
