<?php

namespace milkyway\shop\models\table;

use cheatsheet\Time;
use milkyway\language\models\table\LanguageTable;
use Yii;
use yii\db\ActiveRecord;

class ShopLanguageTable extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return 'shop_language';
    }


    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function getMetadata($data)
    {
        if (array_key_exists($data, $this->metadata)) return $this->metadata[$data];
        return null;
    }

    public function getShopHasOne()
    {
        return $this->hasOne(ShopTable::class, ['id' => 'shop_id']);
    }

    public function getLanguageHasOne()
    {
        return $this->hasOne(LanguageTable::class, ['id' => 'language_id']);
    }
}
