<?php

namespace milkyway\label\models\table;

use cheatsheet\Time;
use Yii;
use yii\db\ActiveRecord;

class LabelTable extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return 'label';
    }

    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public static function getLabel($label, $language = null, $data_cache = YII2_CACHE)
    {
        $language = $language ?: Yii::$app->language;
        $cache = Yii::$app->cache;
        $key = 'redis-label-get-label-' . $label . '-' . $language;
        $data = $cache->get($key);
        if ($data == false || (defined('YII2_CACHE') && YII2_CACHE === false) || $data_cache === false) {
            $query = self::find()->where([self::tableName() . '.label' => $label, self::tableName() . '.language' => $language]);
            $data = $query->one();
            if(defined('YII2_CACHE') && YII2_CACHE === true) $cache->set($key, $data);
        }
        return $data;
    }
}
