<?php
namespace milkyway\label\components;

use backend\components\MyController;

class MyLabelController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
