<?php
namespace modava\tags\components;

use backend\components\MyController;

class MyTagsController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
