<?php
namespace milkyway\freetype\components;

use backend\components\MyController;

class MyFreetypeController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
