<?php

namespace milkyway\news\models;

use common\helpers\MyHelper;
use common\models\User;
use milkyway\news\NewsModule;
use milkyway\news\models\table\NewsImagesTable;
use yii\db\ActiveRecord;
use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "news_images".
 *
 * @property int $id
 * @property int $news_id
 * @property string $image
 * @property int $type Loại hình ảnh
 *
 * @property News $news
 */
class NewsImages extends NewsImagesTable
{
    const SCENARIO_UPDATE = 'update';
    public $toastr_key = 'news-images';
    public $iptImage;

    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
            ]
        );
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['news_id'], 'required', 'on' => self::SCENARIO_UPDATE],
            [['news_id'], 'integer', 'on' => self::SCENARIO_UPDATE],
            [['news_id'], 'exist', 'skipOnError' => true, 'targetClass' => News::class, 'targetAttribute' => ['news_id' => 'id'], 'on' => self::SCENARIO_UPDATE],
            [['type'], 'integer'],
            [['image'], 'string', 'max' => 255],
            [['iptImage'], 'file', 'maxSize' => 2 * 1024 * 1024, 'extensions' => ['png', 'jpg', 'jpeg'], 'wrongExtension' => 'Chỉ chấp nhận định dạng: {extension}']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => NewsModule::t('news', 'ID'),
            'news_id' => NewsModule::t('news', 'News ID'),
            'image' => NewsModule::t('news', 'Image'),
            'iptImage' => NewsModule::t('news', 'Image'),
            'type' => NewsModule::t('news', 'Type'),
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        /* @var $iptImage UploadedFile */
        $image = $this->getAttribute('image');
        $iptImage = $this->iptImage;
        if ($iptImage != null) {
            $imageName = $iptImage->baseName . '-' . time() . '.' . $iptImage->extension;
            if ($iptImage->saveAs($this->pathImage . '/' . $imageName)) {
                $this->updateAttributes([
                    'image' => $imageName
                ]);
                if ($image != null) {
                    @unlink($this->pathImage . '/' . $image);
                }
            }
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
