<?php

namespace milkyway\team\models;

use common\helpers\MyHelper;
use common\models\User;
use milkyway\team\TeamModule;
use milkyway\team\models\table\TeamTable;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\SluggableBehavior;
use yii\db\ActiveRecord;
use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "team".
 *
 * @property int $id
 * @property string $name
 * @property string $slug
 * @property int $category
 * @property string $image
 * @property string $position
 * @property int $status 0: disabled, 1: published
 * @property int $sort
 * @property int $created_at
 * @property int $created_by
 * @property int $updated_at
 * @property int $updated_by
 *
 * @property TeamCategory $category0
 * @property User $createdBy
 * @property User $updatedBy
 */
class Team extends TeamTable
{
    public $toastr_key = 'team';
    public $iptImage;
    private $oldImage;

    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'slug' => [
                    'class' => SluggableBehavior::class,
                    'immutable' => false,
                    'ensureUnique' => true,
                    'value' => function () {
                        return MyHelper::createAlias($this->name);
                    }
                ],
                [
                    'class' => BlameableBehavior::class,
                    'createdByAttribute' => 'created_by',
                    'updatedByAttribute' => 'updated_by',
                ],
                'timestamp' => [
                    'class' => 'yii\behaviors\TimestampBehavior',
                    'preserveNonEmptyValues' => true,
                    'attributes' => [
                        ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                        ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                    ],
                ],
            ]
        );
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'slug', 'category'], 'required'],
            [['category', 'status', 'sort'], 'integer'],
            [['name', 'slug', 'image', 'position'], 'string', 'max' => 255],
            [['category'], 'exist', 'skipOnError' => true, 'targetClass' => TeamCategory::class, 'targetAttribute' => ['category' => 'id']],
            [['iptImage'], 'file', 'extensions' => ['jpg', 'jpeg', 'png'], 'maxSize' => 2 * 1024 * 1024, 'wrongExtension' => 'Chỉ chấp nhận định dạng file: {extensions}'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => TeamModule::t('team', 'ID'),
            'name' => TeamModule::t('team', 'Name'),
            'slug' => TeamModule::t('team', 'Slug'),
            'category' => TeamModule::t('team', 'Category'),
            'image' => TeamModule::t('team', 'Image'),
            'position' => TeamModule::t('team', 'Position'),
            'status' => TeamModule::t('team', 'Status'),
            'sort' => TeamModule::t('team', 'Sort'),
            'created_at' => TeamModule::t('team', 'Created At'),
            'created_by' => TeamModule::t('team', 'Created By'),
            'updated_at' => TeamModule::t('team', 'Updated At'),
            'updated_by' => TeamModule::t('team', 'Updated By'),
        ];
    }

    public function beforeSave($insert)
    {
        $this->oldImage = $this->getOldAttribute('image');
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $iptImage = UploadedFile::getInstance($this, 'iptImage');
        if ($iptImage != null) {
            $imageName = $iptImage->baseName . '-' . time() . '.' . $iptImage->extension;
            if ($iptImage->saveAs($this->pathImage . '/' . $imageName)) {
                $this->updateAttributes([
                    'image' => $imageName
                ]);
                if (file_exists($this->pathImage . '/' . $this->oldImage)) {
                    @unlink($this->pathImage . '/' . $this->oldImage);
                }
            }
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function afterDelete()
    {
        if ($this->image != null && file_exists($this->pathImage . '/' . $this->image)) {
            @unlink($this->pathImage . '/' . $this->image);
        }
        return parent::afterDelete(); // TODO: Change the autogenerated stub
    }
}
