<?php
namespace milkyway\socials\components;

use backend\components\MyController;

class MySocialsController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
