<?php

namespace milkyway\language\models\table;

use cheatsheet\Time;
use common\models\User;
use milkyway\language\models\query\LanguageQuery;
use Yii;
use yii\db\ActiveRecord;

class LanguageTable extends \yii\db\ActiveRecord
{
    const STATUS_DISABLED = 0;
    const STATUS_PUBLISHED = 1;
    public $pathImage;
    public $urlImage;

    public function init()
    {
        $this->pathImage = Yii::getAlias('@frontend/web/uploads/language');
        $this->urlImage = Yii::getAlias('@frontendUrl/uploads/language');
        parent::init(); // TODO: Change the autogenerated stub
    }

    public static function tableName()
    {
        return 'language';
    }

    public static function find()
    {
        return new LanguageQuery(get_called_class());
    }

    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [
            'redis-language-get-by-id-' . $this->id,
            'redis-language-get-by-code-' . $this->code,
            'redis-language-get-by-all',
            'redis-language-get-default-language'
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        if ($this->image != null && !is_dir($this->pathImage . '/' . $this->image) && file_exists($this->pathImage . '/' . $this->image)) {
            @unlink($this->pathImage . '/' . $this->image);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [
            'redis-language-get-by-id-' . $this->id,
            'redis-language-get-by-code-' . $this->code,
            'redis-language-get-by-all',
            'redis-language-get-default-language'
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function getImage()
    {
        if ($this->image == null || is_dir($this->pathImage . '/' . $this->image) || !file_exists($this->pathImage . '/' . $this->image)) return null;
        return Yii::$app->assetManager->publish($this->pathImage . '/' . $this->image);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUserCreated()
    {
        return $this->hasOne(User::class, ['id' => 'created_by']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUserUpdated()
    {
        return $this->hasOne(User::class, ['id' => 'updated_by']);
    }

    public static function getById($id)
    {
        $cache = Yii::$app->cache;
        $key = 'redis-language-get-by-id-' . $id;
        $data = $cache->get($key);
        if ($data == false || !defined('YII2_CACHE') || YII2_CACHE === false) {
            $query = self::find()->where([self::tableName() . '.id' => $id]);
            $data = $query->one();
            if (defined('YII2_CACHE') && YII2_CACHE === true) $cache->set($key, $data);
        }
        return $data;
    }

    public static function getByCode($code)
    {
        $cache = Yii::$app->cache;
        $key = 'redis-language-get-by-code-' . $code;
        $data = $cache->get($key);
        if ($data == false || !defined('YII2_CACHE') || YII2_CACHE === false) {
            $query = self::find()->where([self::tableName() . '.code' => $code]);
            $data = $query->one();
            if (defined('YII2_CACHE') && YII2_CACHE === true) $cache->set($key, $data);
        }
        return $data;
    }

    public static function getAll()
    {
        $cache = Yii::$app->cache;
        $key = 'redis-language-get-by-all';
        $data = $cache->get($key);
        if ($data == false || !defined('YII2_CACHE') || YII2_CACHE === false) {
            $query = self::find()->published()->sort();
            $data = $query->all();
            if (defined('YII2_CACHE') && YII2_CACHE === true) $cache->set($key, $data);
        }
        return $data;
    }

    public static function getDefaultLanguage($data_cache = YII2_CACHE)
    {
        $cache = Yii::$app->cache;
        $key = 'redis-language-get-default-language';
        $data = $cache->get($key);
        if ($data == false || $data_cache === false) {
            $query = self::find()->where([self::tableName() . '.is_default' => self::STATUS_PUBLISHED])->published()->sort();
            if ($query->count() <= 0) $query = self::find()->published()->sort();
            $data = $query->one();
            if (defined('YII2_CACHE') && YII2_CACHE === true) $cache->set($key, $data);
        }
        return $data;
    }
}
