<?php
/**
 * Created by PhpStorm.
 * User: luken
 * Date: 7/2/2020
 * Time: 19:32
 */

namespace frontend\widgets;

use frontend\models\Freetype;
use frontend\models\NewsCategory;
use yii\base\Widget;

class FooterWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $footer_info = Freetype::getOneByType(Freetype::TYPE_FOOTER_INFO);
        $menu_footer = NewsCategory::getMenu(NewsCategory::TYPE_SUPPORT, null, null, true, [], '');
        return $this->render('footer', [
            'footer_info' => $footer_info,
            'menu_footer' => $menu_footer
        ]);
    }
}