<?php
/**
 * Created by PhpStorm.
 * User: luken
 * Date: 7/2/2020
 * Time: 19:31
 */

namespace frontend\widgets;

use frontend\models\NewsCategory;
use yii\base\Widget;

class HeaderWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $menu = NewsCategory::getMenuMain();
        return $this->render('header', [
            'menu' => $menu,
        ]);
    }
}