<?php
/**
 * Created by PhpStorm.
 * User: luken
 * Date: 7/8/2020
 * Time: 14:59
 */

namespace frontend\widgets;


use frontend\models\News;
use frontend\models\NewsCategory;
use yii\base\Widget;

class NewsFeatured extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $list_news_featured = News::getNewsCheckCamNangXayDung(NewsCategory::TYPE_NEWS, false);
        if (count($list_news_featured) <= 0) return null;
        return $this->render('news-featured', [
            'list_news_featured' => $list_news_featured
        ]);
    }
}