<?php
/**
 * Created by PhpStorm.
 * User: luken
 * Date: 7/8/2020
 * Time: 14:09
 */

namespace frontend\widgets;


use frontend\models\News;
use yii\base\Widget;

class NewsRecommendWidget extends Widget
{
    public $news_id = null;
    public $limit = null;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $recommend_news = News::getRecommendNews($this->news_id, $this->limit, false);
        if (count($recommend_news) <= 0) return null;
        return $this->render('news-recommend', [
            'recommend_news' => $recommend_news
        ]);
    }
}