<?php
/**
 * Created by PhpStorm.
 * User: luken
 * Date: 7/8/2020
 * Time: 14:59
 */

namespace frontend\widgets;


use yii\base\Widget;

class NewsFeatured extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('news-featured', []);
    }
}