<?php
/**
 * Created by PhpStorm.
 * User: luken
 * Date: 7/14/2020
 * Time: 11:43
 */

namespace frontend\widgets;


use frontend\models\Slider;
use yii\base\ViewNotFoundException;
use yii\base\Widget;

class SliderWidget extends Widget
{
    public $type;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $slider = Slider::getByType($this->type);
        if (count($slider) <= 0) return null;

        $view = $this->type == Slider::TYPE_SLIDER ? 'slider' : 'partner';

        try {
            return $this->render($view, [
                'sliders' => $slider
            ]);
        } catch (ViewNotFoundException $exception) {
            return null;
        }
    }
}