<?php
/**
 * Created by PhpStorm.
 * User: luken
 * Date: 7/14/2020
 * Time: 11:43
 */

namespace frontend\widgets;


use yii\base\Widget;

class SliderWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('slider', []);
    }
}