<?php
namespace milkyway\shop\components;

use backend\components\MyController;

class MyShopController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
