<?php
namespace milkyway\language\components;

use backend\components\MyController;

class MyLanguageController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
