<?php
namespace milkyway\slider\components;

use backend\components\MyController;

class MySliderController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
