<?php
namespace milkyway\partner\components;

use backend\components\MyController;

class MyPartnerController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
